title: Aristocat-A
description: Hi there, my name is Aristocat A.

url: https://aristocat-blog.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: aristocat-a
  twitter: aristocat-a
  facebook: aristocat-a
  email: aristocat-a
  linkedin: aristocat-a

google_analytics: # "UA-58263416-1"

disqus:
    shortname: aristocat-a
